/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChildrenCard: typeof import('./src/components/childrenCard/index.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NTooltip: typeof import('naive-ui')['NTooltip']
  }
}
